---
title: |
    | Planejamento e Análise de Experimentos (EEE933)
    | Estudo de Caso 2
#title: Planejamento e Análise de Experimentos (EEE933) Estudo de Caso 1
author: Pedro Vinícius, Samara Silva e Savio Vieira
date: 24 de Agosto de 2020
output:
  pdf_document:
    fig_caption: yes
  html_document:
    df_print: paged
indent: true
header-includes: 
    - \usepackage{indentfirst}
    - \usepackage{float}
bibliography: ref.bib
doi: https://github.com/pedbrgs/Design-and-Analysis-of-Experiments
pagetitle: Estudo de Caso 2
---

```{r setup, results='hide', warning=FALSE, include = FALSE, message = FALSE, echo=FALSE}
# A few initial definitions just to make sure all required packages are installed. Change as needed.
# NOTE: It may echo some weird messages to the PDF on the first compile (package installation messages). Run twice and the problem will (hopefully) go away. 
if (!require(ggplot2, quietly = TRUE)){
      install.packages("ggplot2")
      }
if (!require(devtools, quietly = TRUE)){
      install.packages("devtools")
      }
 if (!require(broom, quietly = TRUE)){
       devtools::install_github("dgrtwo/broom")
      }
if (!require(stats, quietly = TRUE)){
      suppressMessages(install.packages("stats"))
      }
if (!require(plotly, quietly = TRUE)){
      suppressMessages(install.packages("plotly"))
      }
if (!require(reshape2, quietly = TRUE)){
      suppressMessages(install.packages("reshape2"))
      }
```


```{r, message = FALSE, warning = FALSE, results = 'hide', echo = FALSE}
# Statistical package 
library(stats)
# Ggplot2 package
library(ggplot2)
# Plotly package
library(plotly)
# Reshape2 package
library(reshape2)
# UFT-8 Encoding
options(Encoding="UTF-8")
```

# Introdução

## Planejamento dos Experimentos

$$\begin{cases} H_0: \mu_{2016} = \mu_{2017} &\\H_1: \mu_{2016} \neq \mu_{2017} \end{cases}$$

## Tratamento dos Dados

```{r}
# Carrega dados relativos ao semestre de 2016/2
data2016 <- read.csv('imc_20162.csv')
# Seleciona apenas alunos do programa de pós-graduação
ppgee2016 <- data2016[data2016['Course'] == 'PPGEE',]
# Separa amostras por sexo
female2016 <- ppgee2016[ppgee2016['Gender'] == 'F',]
male2016 <- ppgee2016[ppgee2016['Gender'] == 'M',]
```

```{r}
# Carrega dados relativos ao semestre de 2017/2
data2017 <- read.csv('CS01_20172.csv', sep = ';')
# Separa amostras por sexo
female2017 <- data2017[data2017['Sex'] == 'F',]
male2017 <- data2017[data2017['Sex'] == 'M',]
```

```{r}
# Cálculo do Índice de Massa Corporal (IMC)

# Alunos de 2016/2
female2016['IMC.kg/m2'] <- female2016['Weight.kg']/(female2016['Height.m']^2)
male2016['IMC.kg/m2'] <- male2016['Weight.kg']/(male2016['Height.m']^2)

# Alunos de 2017/2
female2017['IMC.kg/m2'] <- female2017['Weight.kg']/(female2017['height.m']^2)
male2017['IMC.kg/m2'] <- male2017['Weight.kg']/(male2017['height.m']^2)
```

```{r, results = 'hide', echo = FALSE}

# Amostras de 2016/2
F2016 <- female2016$`IMC.kg/m2`
M2016 <- male2016$`IMC.kg/m2`

# Amostras de 2017/2
F2017 <- female2017$`IMC.kg/m2`
M2017 <- male2017$`IMC.kg/m2`
```

```{r, results = 'hide', echo = FALSE}
n_max <- max(length(F2016), length(F2017), length(M2016), length(M2017))
length(F2016) <- n_max
length(F2017) <- n_max
length(M2016) <- n_max
length(M2017) <- n_max

IMCs <- data.frame('M2016' = M2016, 'M2017' = M2017, 'F2016' = F2016, 'F2017' = F2017)
IMCs <- melt(IMCs, id.vars = NULL)
IMCs <- na.omit(IMCs)
```

## Análise Exploratória de Dados

```{r plottol, fig.height = 3, fig.width = 6, fig.align = 'center', fig.cap = 'Boxplots.', fig.pos = 'H'}
# Boxplot
boxplot <- ggplot(data = IMCs, mapping = aes(x = variable, y = value)) + 
          geom_boxplot(lwd = 0.3) 
boxplot
```

## Validação de Premissas

```{r}
shapiro.test(M2016)
shapiro.test(M2017)
```

```{r}
shapiro.test(F2016)
shapiro.test(F2017)
```

## Análise Estatística

```{r}
(t_test <- t.test(x = M2016, 
                  y = M2017,
                mu = 0, 
                alternative = "two.sided",
                conf.level = 0.95))
cat('Intervalo de confiança:', t_test$conf.int[1:2])
```

```{r}
wilcox.test(x = F2016, y = F2017, alternative = "two.sided")
```

## Conclusões


### Discussão de Melhorias


### Atividades Desempenhadas



\renewcommand\refname{Referências}
\bibliographystyle{plain}
\bibliography{ref}